### ISSUE TITLE
可以提供个安装包吗

### ISSUE THREAD

**Issue by kinpowoo** [Gsangu/KugouDownloader#3]

**Comment by C-Li** [comment]
[KugouDownloader](https://github.com/C-Li/KugouDownloader/blob/master/%E9%85%B7%E7%8B%97%E6%97%A0%E6%8D%9F%E9%9F%B3%E4%B9%90%E4%B8%8B%E8%BD%BD/bin/Debug/%E7%A8%8B%E5%BA%8F%E5%8C%85.7z)
点右边的Download下载
解压后就可以运行
