### ISSUE TITLE
抓包显示搜索数据很多，但是列表显示数据好少

### ISSUE THREAD

**Issue by zhangliangming** [Gsangu/KugouDownloader#7]
你好，我运行了软件，抓了一下包，发现搜索接口返回的数据是好多的，但是在列表显示的才几条。是不是酷狗的http://trackercdn.kugou.com，这个地址，有些歌曲不能用？

**Comment by Gsangu** [comment]
只拿接口里面无损格式的数据，没有无损的不拿。接口见
https://github.com/Gsangu/KugouDownloader/blob/7c6dfd208727059c14e99380abedc42e070965b0/%E9%85%B7%E7%8B%97%E6%97%A0%E6%8D%9F%E9%9F%B3%E4%B9%90%E4%B8%8B%E8%BD%BD/Form1.cs#L123

**Comment by zhangliangming** [comment]
@Gsangu 感谢。
